services:
  backend:
    build:
      context: ./chatbot-app/backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      LLAMA_API_URL: ${LLAMA_API_URL}
      PYTHONUNBUFFERED: 1
    networks:
      - chatbot-net
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  frontend:
    build: ./frontend/frontend-chatbot
    container_name: chatbot-frontend
    expose:
      - "80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chatbot-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - chatbot-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - chatbot-net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/login"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
      grafana:
        condition: service_healthy
      prometheus:
        condition: service_healthy
    networks:
      - chatbot-net

networks:
  chatbot-net: {}
