services:
  backend:
    build:
      context: ./chatbot-app/backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - chatbot-net
    .env_file:
      - ./backend/.env

  frontend:
    build: ./frontend/frontend-chatbot
    container_name: chatbot-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chatbot-net

  #  # Optional: PostgreSQL Database
  # db:
  #   image: postgres:15
  #   container_name: chatbot-db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: chatbot
  #     POSTGRES_PASSWORD: chatbot123
  #     POSTGRES_DB: chatbotdb
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - chatbot-net

networks:
  chatbot-net: {}
# volumes:
#   db_data: {}
