services:
  backend:
    build:
      context: ./chatbot-app/backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      LLAMA_API_URL: ${LLAMA_API_URL}
      PYTHONUNBUFFERED: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - chatbot-net

  frontend:
    build: ./frontend/frontend-chatbot
    container_name: chatbot-frontend
    expose:
      - "80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - chatbot-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - chatbot-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - chatbot-net

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - chatbot-net

networks:
  chatbot-net: {}
